version: '3.8'

services:
  backend:
    build: ./backend
    container_name: go_api
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    networks:
      - host
