version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: go_api
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env

volumes:
  db-data:
