name: Build, Push Docker Images, and Run Go Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_FRONTEND: ${{ github.repository }}/frontend
      IMAGE_BACKEND: ${{ github.repository }}/backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

#    - name: Build and push frontend image
#      uses: docker/build-push-action@v2
#      with:
#        context: ./frontend
#        push: true
#        tags: |
#          ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}:latest

    - name: Build and push backend image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:latest

  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 963233
          MYSQL_DATABASE: MelkOnline
        ports:
          - 3306:3306

      redis:
        image: redis:alpine
        env:
          REDIS_PASSWORD: redispass
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up TMATE
      uses: mxschmitt/action-tmate@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'


    - name: Install dependencies
      run: go mod tidy
      working-directory: ./backend/cmd


    - name: Run unit tests
      run: go test ./... -v
      working-directory: ./backend/test/infrastructure
